language: cpp
compiler:
  - gcc
script: make
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libncursesw5-dev liblua5.1-0-dev pkg-config libpcre3-dev libgmime-2.6-dev libglibmm-2.4-dev