sudo: required
dist: trusty
install:
- export CC="g++-4.8"
- ${CC} --version
addons:
  apt:
    packages:
    - libncursesw5-dev
    - libncursesw5-dev
    - liblua5.1-0-dev
    - pkg-config
    - libpcre3-dev
    - libgmime-2.6-dev
    - libmagic-dev
env:
    - LUA_VERSION=5.1
language: cpp
compiler:
  - g++
script:
  - make
  - make test
  - make test-lua

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libncursesw5-dev liblua5.1-0-dev pkg-config libpcre3-dev libgmime-2.6-dev
